export const LOADING = 'LOADING';
export const LOADING_FOR_NEXT = 'LOADING_FOR_NEXT';
export const DONE = 'DONE';
export const UPDATE_DONE = 'UPDATE_DONE';
export const IDLE = 'IDLE';
export const SET_DRAWER = 'SET_DRAWER';

export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const USER_PROFILE_LOADING = 'USER_PROFILE_LOADING';
export const USER_PROFILE_DONE = 'USER_PROFILE_DONE';



//NEWS
export const GET_NEWS_LOADING = 'GET_NEWS_LOADING';
export const GET_NEWS_LOADING_FOR_NEXT = 'GET_NEWS_LOADING_FOR_NEXT';
export const GET_NEWS_DONE = 'GET_NEWS_DONE';


//REWARDS
export const GET_REWARDS_LOADING = 'GET_REWARDS_LOADING';
export const GET_REWARDS_LOADING_FOR_NEXT = 'GET_REWARDS_LOADING_FOR_NEXT';
export const GET_REWARDS_DONE = 'GET_REWARDS_DONE';